#!/usr/bin/env bash

#######################################
##############   Config   #############
#######################################

# load sxhkd for hotkeys
pgrep -x sxhkd > /dev/null || sxhkd &
# each window's name
bspc monitor -d I II III IV V VI VII VIII IX X
picom & # compositor

polybar & # status bar
feh --bg-scale ~/.config/wallpapers/wallpaper.png & # Wallpaper
# INFO: Adjust the delay before key repetition starts
# 250 => delay in ms
# 25 => chars per second
xset r rate 250 30 &

#######################################
##############   Window   #############
#######################################

bspc config border_width 0
bspc config window_gap 0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


#######################################
##############   Colors   #############
#######################################

bspc config normal_border_color "#232136"
bspc config active_border_color "#31748f"
bspc config focused_border_color "#907aa9"
bspc config presel_feedback_color "#eb6f92"
