#!/usr/bin/env bash

#######################################
##############   Config   #############
#######################################


if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
  xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x123 --rotate normal --output HDMI-1 --mode 1920x1200 --pos 1920x0 --rotate normal --output DP-1 --off --output DP-2 --off
fi

# load sxhkd for hotkeys
pgrep -x sxhkd > /dev/null || sxhkd &

pkill -x polybar
polybar & # status bar
xset s off -dpms s noblank

# each window's name
# bspc monitor -d I II III IV V VI VII VIII IX X

# set the default desktop for each monitor

# if HDMI-1 monitor is not connected, make eDO-1 take all screens
if [[ $(xrandr -q | grep 'HDMI-1 connected') == "" ]]; then
  bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
# if HDMI-1 monitor is connected, make eDO-1 take only the primary screen
else
  bspc monitor eDP-1 -d I II
  bspc monitor HDMI-1 -d III IV V VI VII VIII IX X
fi

picom & # compositor

feh --bg-scale ~/.config/wallpapers/wallpaper-6.jpg & # Wallpaper
# INFO: Adjust the delay before key repetition starts
# 250 => delay in ms
# 25 => chars per second
xset r rate 250 30 &

#######################################
##############   Window   #############
#######################################

bspc config border_width 0
bspc config window_gap 10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


#######################################
##############   Colors   #############
#######################################

# bspc config focused_border_color "#9ccfd8"
bspc config focused_border_color "#fefefe"
bspc config normal_border_color "#6e6a86"
bspc rule -a zoom state=floating
