import = ["~/.config/alacritty/rose-pine-moon.toml"]

[window]
decorations = "None"
padding = { x = 5, y = 5 }
opacity = 0.7

dimensions = { columns = 120, lines = 45 }

# startup_mode = "Fullscreen"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 8

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 400

[colors.cursor]
text = "#e0def4"
cursor = "#827f97"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[colors.primary]
background = "#111111"
