[colors.primary]
foreground = "#d1d1d1"
background = "#111111"
dim_foreground = "#808080"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#141414"
cursor = "#d1d1d1"

[colors.vi_mode_cursor]
text = "#141414"
cursor = "#d1d1d1"

[colors.search.matches]
foreground = "#141414"
background = "#666666"

[colors.search.focused_match]
foreground = "#141414"
background = "#955f6d"  # Muted red

[colors.hints.start]
foreground = "#666666"
background = "#1a1a1a"

[colors.hints.end]
foreground = "#333333"
background = "#1a1a1a"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#d1d1d1"
background = "#1a1a1a"

[colors.selection]
text = "#d1d1d1"
background = "#333333"

[colors.normal]
black = "#1a1a1a"
red = "#955f6d"      # Muted red
green = "#d1d1d1"    # Monochrome
yellow = "#a88d6f"   # Muted yellow
blue = "#d1d1d1"     # Monochrome
magenta = "#d1d1d1"  # Monochrome
cyan = "#6e8b93"     # Muted blue-grey
white = "#d1d1d1"

[colors.bright]
black = "#666666"
red = "#955f6d"
green = "#e0e0e0"
yellow = "#a88d6f"
blue = "#e0e0e0"
magenta = "#e0e0e0"
cyan = "#6e8b93"
white = "#ffffff"

[colors.dim]
black = "#333333"
red = "#955f6d"
green = "#808080"
yellow = "#a88d6f"
blue = "#808080"
magenta = "#808080"
cyan = "#6e8b93"
white = "#a0a0a0"
