[colors.primary]
foreground = "#BBC3D4"    # white0
background = "#111111"     # custom background
dim_foreground = "#3B4252" # gray2
bright_foreground = "#ECEFF4" # white3

[colors.cursor]
text = "#BBC3D4"    # white0
cursor = "#2E3440"  # gray1

[colors.vi_mode_cursor]
text = "#BBC3D4"    # white0
cursor = "#2E3440"  # gray1

[colors.search.matches]
foreground = "#BBC3D4" # white0
background = "#242933" # gray0

[colors.search.focused_match]
foreground = "#191D24" # black0
background = "#BF616A" # red

[colors.hints.start]
foreground = "#434C5E" # gray3
background = "#1E222A" # black1

[colors.hints.end]
foreground = "#3B4252" # gray2
background = "#1E222A" # black1

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#BBC3D4" # white0
background = "#1E222A" # black1

[colors.selection]
text = "#BBC3D4"    # white0
background = "#242933" # gray0

[colors.normal]
black = "#191D24"   # black0
red = "#BF616A"     # red
green = "#A3BE8C"   # green
yellow = "#EBCB8B"  # yellow
blue = "#5E81AC"    # blue0
magenta = "#B48EAD" # magenta
cyan = "#8FBCBB"    # cyan
white = "#BBC3D4"   # white0

[colors.bright]
black = "#222630"   # black2
red = "#C5727A"     # red_b
green = "#B1C88D"   # green_b
yellow = "#EFD49F"  # yellow_b
blue = "#81A1C1"    # blue1
magenta = "#BE9DB8" # magenta_b
cyan = "#9FC6C5"    # cyan_b
white = "#ECEFF4"   # white3

[colors.dim]
black = "#1E222A"   # black1
red = "#B74E58"     # red_d
green = "#97B67C"   # green_d
yellow = "#E7C173"  # yellow_d
blue = "#88C0D0"    # blue2
magenta = "#A97EA1" # magenta_d
cyan = "#80B3B2"    # cyan_d
white = "#D8DEE9"   # white1
