;; name: Lackluster

[colors]
;; Base
background = #aa111111
;; Highlight Med
background-alt = #aa111111

;; Text
foreground = #CCCCCC

;; Primary
primary = #AAAAAA
; primary = #708090

;; Secondary
secondary = #7A7A7A

;; Alert
alert = #D70000

;; Muted / Disabled
disabled = #555555
